---
provisioner:
  name: chef_zero
  require_chef_omnibus: latest

driver:
  name: vagrant
  customize:
    memory: 512

platforms:
  - name: centos-6.4
  - name: ubuntu-12.04

suites:
- name: default
  run_list:
    - recipe[ktc-testing]
    - recipe[etcd::compile_time]
    - recipe[ktc-monitor::client]
    - recipe[ktc-messaging]
  attributes:
    etcd:
      args: '-c 127.0.0.1:4001 -s 127.0.0.1:7001'
      servers:
        - 127.0.0.1
    ha_disabled: true
    openstack:
      developer_mode: true
