---
provisioner:
  name: chef_zero
  require_chef_omnibus: latest

driver:
  name: vagrant
  customize:
    memory: 512

platforms:
  - name: centos-6.4
  - name: ubuntu-12.04

suites:
  - name: default
    run_list:
      - recipe[ktc-testing]
      - recipe[etcd::compile_time]
      - recipe[ktc-messaging]
    attributes:
      ktc:
        monitor: false
      etcd:
        servers:
          - 127.0.0.1
      ha_disabled: true
      openstack:
        developer_mode: true
