name             'ktc-messaging'
maintainer       'KT Cloudware, Inc.'
maintainer_email 'wil.reichert@kt.com'
license          'All rights reserved'
description      'Installs/Configures ktc-messaging'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version '1.0.18'

depends 'ktc-openstack-ha'
depends 'openstack-common'
depends 'ktc-monitor'
depends 'ktc-utils'
depends 'rabbitmq', '>= 2.4.0'
depends 'services', '>= 2.0.3'
depends 'users'
